CREATE TABLE car(car_id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
model VARCHAR (70) NOT NULL,
description VARCHAR(100) NOT NULL,
year VARCHAR(4) NOT NULL,image TEXT NOT NULL,
condition VARCHAR NOT NULL,
installment NUMERIC(5,2) NOT NULL,
price INT NOT NULL);